Use time_t to store time data.
This fixes the build on 32-bit FreeBSD releases, which were failing like this:

src/CReplayData.cpp: In member function 'void ReplayData::printReplayInformation()':
src/CReplayData.cpp:41: error: invalid conversion from 'long int*' to 'const time_t*'
src/CReplayData.cpp:41: error:   initializing argument 1 of 'tm* localtime(const time_t*)'